namespace FluentChat
{
    [default_interface]
    runtimeclass AddGroup : Microsoft.UI.Xaml.Controls.UserControl
    {
        AddGroup();
        static String GetGroupId(Windows.Data.Json.JsonObject jsonObject);
    }
}
