import "UserViewModel.idl";
import "ChatViewModel.idl";
import "TransportService.idl";

namespace FluentChat
{
	[default_interface]
	runtimeclass AppViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
	{
		AppViewModel();
		UserViewModel UserViewModel{ get; };
		ChatViewModel ChatViewModel{ get; };
		TransportService TransportService{ get; };
		void OpenMainWindow();
		void OpenStartWindow();
	}
}
