import "UserViewModel.idl";
import "TransportService.idl";

namespace FluentChat
{
	[default_interface]
	runtimeclass AppViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
	{
		AppViewModel();
		UserViewModel UserViewModel { get; };
		TransportService TransportService { get; };
	}
}
