import "UserViewModel.idl";

namespace FluentChat
{
	[default_interface]
	runtimeclass AppViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		AppViewModel();
		UserViewModel UserViewModel{ get; };
	}
}
