namespace FluentChat
{
    [default_interface]
    runtimeclass ChatViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ChatViewModel();
        Windows.Data.Json.JsonObject ChatInfo;
        Int32 ChatType;
        Int32 ChatView;
    }
}
