import "AppViewModel.idl";

namespace FluentChat
{
    [default_interface]
    runtimeclass ChatGroup : Microsoft.UI.Xaml.Controls.UserControl
    {
        ChatGroup();
        AppViewModel AppViewModel{ get; };
        static Microsoft.UI.Xaml.HorizontalAlignment BubblePositionConverter(Windows.Data.Json.JsonObject args);
        static String DisplayNameConverter(Windows.Data.Json.JsonObject args);
    }
}
