import "AppViewModel.idl";

namespace FluentChat
{
    [default_interface]
    runtimeclass LoginPage : Microsoft.UI.Xaml.Controls.Page
    {
        LoginPage();
        AppViewModel AppViewModel{ get; };
    }
}
