import "AppViewModel.idl";

namespace FluentChat
{
    [default_interface]
    runtimeclass SettingsPage : Microsoft.UI.Xaml.Controls.Page, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        SettingsPage();
        AppViewModel AppViewModel{ get; };
    }
}
