namespace FluentChat
{
    [default_interface]
    runtimeclass UserViewModel : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        UserViewModel();
        String NickName;
        String Email;
        String Password;
    }
}
