namespace FluentChat
{
    [default_interface]
    runtimeclass UserViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        UserViewModel();
        String NickName;
        String Email;
        String Password;
        Boolean IsLogin;
    }
}
